# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9bb236da53bb25f2a277ec5c5f90cf54f206d996ac4c004ac5210537b3df707c6c5514c5c6d4e373699f6713fa7e4be608c2694f783912c74f45b529293c0022

test:
  secret_key_base: 65a7b900c0a9d7bce3369d7a1cbd929688d0b7848340102395c2474c119e31eca853bd99396e54759b76e47dc8f099c25398c3361d303bc6083f97bc3d03c52c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
